AsyncInn.Web/Models/AmenitySummary.cs
namespace AsyncInn.Web.Models
{
    public class AmenitySummary
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

AsyncInn.Web/Models/ErrorViewModel.cs
using System;

namespace AsyncInn.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AsyncInn.Web/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace AsyncInn.Web.Models
{
    public class Hotel
    {
        //needs to be lowercase
        [JsonPropertyName("id")]
        public long Id { get; set; }


        [JsonPropertyName("hotelName")]
        [Display(Name = "Hotel Name")]
        public string HotelName { get; set; }


        [JsonPropertyName("streetAddress")]
        [Display(Name = "Street Address")]
        public string StreetAddress { get; set; }


        [JsonPropertyName("city")]
        [Display(Name = "City")]
        public string City { get; set; }


        [JsonPropertyName("state")]
        [Display(Name = "State")]
        public string State { get; set; }


        [JsonPropertyName("country")]
        [Display(Name = "Country")]
        public string Country { get; set; }


        public IEnumerable<HotelRoomSummary> HotelRoom { get; set; }
    }


}

AsyncInn.Web/Models/HotelRoomSummary.cs
using System.ComponentModel.DataAnnotations;

namespace AsyncInn.Web.Models
{
    public class HotelRoomSummary
    {
        public long HotelId { get; set; }
        public int RoomNumber { get; set; }
        public string Name { get; set; }

        [Display(Name = "Daily Cost")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        public decimal Rate { get; set; }
        public int RoomID { get; set; }
        public RoomSummary Room { get; set; }
    }
}

AsyncInn.Web/Models/HotelSummary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace AsyncInn.Web.Models
{
    public class HotelSummary
    {
        [JsonPropertyName("Id")]
        public long Id { get; set; }




        [JsonPropertyName("hotelName")]
        [Display(Name = "Hotel Name")]
        public string HotelName { get; set; }


        [JsonPropertyName("streetAddress")]
        [Display(Name = "Street Address")]
        public string StreetAddress { get; set; }


        [JsonPropertyName("city")]
        [Display(Name = "City")]
        public string City { get; set; }


        [JsonPropertyName("state")]
        [Display(Name = "State")]
        public string State { get; set; }


        [JsonPropertyName("country")]
        [Display(Name = "Country")]
        public string Country { get; set; }


        public IEnumerable<HotelRoomSummary> HotelRoom { get; set; }
    }


}

AsyncInn.Web/Models/RoomSummary.cs
using System.Collections.Generic;

namespace AsyncInn.Web.Models
{
    public class RoomSummary
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
        public List<AmenitySummary> Amenities { get; set; }
    }
}

AsyncInn.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AsyncInn.Web.Models;

namespace AsyncInn.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("We showed home!");
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AsyncInn.Web/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AsyncInn.Web.Models;
using AsyncInn.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AsyncInn.Web.Controllers
{
    public class HotelController : Controller
    {
        IHotelService hotelService;

        public HotelController(IHotelService hotelService)
        {
            this.hotelService = hotelService;
        }

        // GET: HotelController
        public async Task<ActionResult> Index()
        {
            var hotels = await hotelService.GetHotels();
            return View(hotels.OrderBy(hotels => hotels.HotelName));
        }

        // GET: HotelController/Details/5
        public async Task<ActionResult> Details(long id)
        {
            var hotel = await hotelService.GetHotelById(id);
            return View(hotel);
        }
        //GET: Hotel/Create
        // GET: HotelController/Delete/5
        public ActionResult Create()
        {
            return View();
        }
        // POST: Hotel/Create
        [HttpPost]
        public async Task <ActionResult> Create(Hotel hotel)
        {
            try
            {

                await hotelService.Create(hotel);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
            
        }
        // Get: HotelController/Edit/5
        public async Task<ActionResult> Edit(long id)
        {
            var hotel = await hotelService.GetHotelById(id);
            return View(hotel);
        }

        // POST: HotelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(long id, Hotel hotel)
        {
            try
            {
                await hotelService.Edit(id, hotel);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HotelController/Delete/5
        public async Task <ActionResult> Delete(long id)
        {
           var hotel = await hotelService.GetHotelById(id);
            return View(hotel);
        }

        // POST: HotelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <ActionResult> Delete(long id, IFormCollection collection)
        {
            try
            {
                await hotelService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AsyncInn.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "_Layout";
}
<h1>@ViewData["Title"]</h1>

<div class="container">
    <div class="card mx-auto">
        <div class="card-body ">
            <h5 class="card-title text-md-center">Marie Antons</h5>
            <h6 class="card-subtitle mb-2 text-muted text-md-center">Junior Developer at STRATAFOLIO</h6>
            <p class="card-text text-md-center">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <div class="text-center">
                <a class="btn btn-primary" href="https://github.com/mrsantons" role="button">GitHub</a>
                <a class="btn btn-primary" href="https://www.linkedin.com/in/marieantons/" role="button">LinkedIn</a>
            </div>
        </div>
    </div>
</div>

AsyncInn.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}


   

<body>
   
    <div class="bodyContainer">

            <text>Async Inn</text>

        <span class="logo"></span>
        <aside>
            <form>
                <div>
                    <label for="username" class="visually-hidden">Username: </label>
                    <input class="username" id="password" placeholder="Username" />
                </div>
                <div>
                    <label for="password" class="visually-hidden">Password: </label>
                    <input class="password" id="password" placeholder="Password" />
                </div>
                <div>
                    <input type="submit" />
                </div>
            </form>
        </aside>


        @*<div>
            <img class="col-md-auto mb-1" src="~/css/Photos/bda2.jpg" />
        </div>
        <div class="d-flex flex-row">
            <div>
                <img class="col-sm-12 m-0 pr-1" src="~/css/Photos/bda.jpg" />
            </div>
            <div>
                <img class="col-sm-12 mb-0 pl-0 " src="~/css/Photos/bda3.jpg" />
            </div>
        </div>*@



    </div>
</body>

AsyncInn.Web/Views/Hotels/Detail.cshtml
@model AsyncInn.Web.Models.Hotel

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HotelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HotelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

AsyncInn.Web/Views/Hotels/Update.cshtml
@model AsyncInn.Web.Models.Hotel

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Hotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelName" class="control-label"></label>
                <input asp-for="HotelName" class="form-control" />
                <span asp-validation-for="HotelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetAddress" class="control-label"></label>
                <input asp-for="StreetAddress" class="form-control" />
                <span asp-validation-for="StreetAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AsyncInn.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Alice&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@800&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/988c5e7e3e.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="navContainer">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index">Hotels</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @RenderSection("Header", required: false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!--where rendering of page-->
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AsyncInn- <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>